[theme]
primaryColor = "#1f77b4"  # Couleur principale (bleu par d√©faut)
backgroundColor = "#1e1e1e"  # Fond sombre
secondaryBackgroundColor = "#31333F"  # Fond secondaire (ex : sidebar)
textColor = "#f0f2f6"  # Texte clair
font = "sans serif"  # Police
